import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import PrimaryLayout from '@/layout/primary-layout/PrimaryLayout';
import RecoilWrapper from '@/lib/RecoilWrapper';
import RegisterModalWrapper from '@/components/register-component/RegisterModalWrapper';
import ReactQueryWrapper from '@/lib/ReactQueryWrapper';
import UserDataWrapper from '@/lib/UserDataWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Web store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <ReactQueryWrapper>
          <RecoilWrapper>
            <UserDataWrapper>
              <PrimaryLayout>{children}</PrimaryLayout>
              <RegisterModalWrapper />
            </UserDataWrapper>
          </RecoilWrapper>
        </ReactQueryWrapper>
      </body>
    </html>
  );
}
